[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Rasmus Göransson <rasmus@volumental.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
failure = "0.1.8"
lazy_static = "1.4.0"
